# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('let', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('total_locality', models.IntegerField(default=0)),
                ('total_venues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_name', models.CharField(max_length=50)),
                ('total_venues', models.IntegerField(default=0)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.City')),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=50)),
                ('venue_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.City')),
                ('venue_locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Locality')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Venues'),
        ),
    ]
