# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='venues',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
