# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20170122_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_slug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='locality_slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
