# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20170122_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='venue_city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='venues.City'),
        ),
        migrations.AlterField(
            model_name='venues',
            name='venue_locality',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='venues.Locality'),
        ),
    ]
