# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapny_name', models.CharField(max_length=100)),
                ('aadhar_card', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='comapny',
        ),
        migrations.AddField(
            model_name='normaluser',
            name='aadhar_card',
            field=models.CharField(default=1234567890, max_length=20),
        ),
    ]
