# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170121_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='contact_no',
            field=models.CharField(default=7770806859L, max_length=11),
            preserve_default=False,
        ),
    ]
