# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_normaluser_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateuser',
            name='contact_no',
            field=models.CharField(default=7770806859L, max_length=11),
            preserve_default=False,
        ),
    ]
