# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_club_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='entry_rate',
            name='entry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Entry_Type'),
        ),
    ]
