# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20170225_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_rate',
            name='entry_type',
            field=models.CharField(max_length=50),
        ),
    ]
