# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20170125_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
