# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tansaction_number',
            field=models.CharField(default=1234567890, max_length=50),
            preserve_default=False,
        ),
    ]
